apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deploy
  labels:
    app: kafka-deploy
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: kafka-deploy-pod
  template:
    metadata:
      labels:
        app: kafka-deploy-pod
    spec:
      containers:
      - name: kafka 
        image: wurstmeister/kafka
        ports:
          - containerPort: 9092
        env:
          - name: KAFKA_ADVERTISED_HOST_NAME
            value: 172.17.0.1
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: localhost:2181
        volumeMounts:
          - mountPath: /var/run/docker.sock
            name: kafka-volume
      volumes:
        - name: kafka-volume
          hostPath:
            path: /var/run/docker.sock
            type: FileOrCreate