kind: Service
apiVersion: v1
metadata:
  name: zookeeper-service-external-name
spec:
  type: NodePort
  selector:
    app: zookeeper-pod
  ports:
  - name: default
    port: 2181
    nodePort: 30500

---


apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  selector:
    app: kafka-deploy-pod
  ports:
  - protocol: TCP
    port: 9092
    targetPort: 9092

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-deploy
  labels:
    app: zookeeper-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-pod
  template:
    metadata:
      labels:
        app: zookeeper-pod
    spec:
      containers:
      - name: zookeeper-pod
        image: wurstmeister/zookeeper
        ports:
          - containerPort: 2181

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deploy
  labels:
    app: kafka-deploy
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: kafka-deploy-pod
  template:
    metadata:
      labels:
        app: kafka-deploy-pod
    spec:
      containers:
      - name: kafka 
        image: wurstmeister/kafka
        ports:
          - containerPort: 9092
        env:
          - name: KAFKA_ADVERTISED_HOST_NAME
            value: 172.17.0.1
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: zookeeper-service-external-name:2181
        volumeMounts:
          - mountPath: /var/run/docker.sock
            name: kafka-volume
      volumes:
        - name: kafka-volume
          hostPath:
            path: /var/run/docker.sock
            type: FileOrCreate
---



