apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service-name
spec:
  clusterIP: None
  selector:
    app: zookeeper-pod
  ports:
  - name: client
    port: 2181
    protocol: TCP
  - name: follower
    port: 2888
    protocol: TCP
  - name: leader
    port: 3888
    protocol: TCP

---


apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  clusterIP: 10.96.41.4
  selector:
    app: kafka-deploy-pod
  ports:
  - protocol: TCP
    port: 9092
    targetPort: 9092

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-deploy
  labels:
    app: zookeeper-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-pod
  template:
    metadata:
      labels:
        app: zookeeper-pod
    spec:
      containers:
      - name: zookeeper-pod
        image: wurstmeister/zookeeper
        ports:
          - containerPort: 2181
          - containerPort: 2888
          - containerPort: 3888

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deploy
  labels:
    app: kafka-deploy
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: kafka-deploy-pod
  template:
    metadata:
      labels:
        app: kafka-deploy-pod
    spec:
      containers:
      - name: kafka 
        image: wurstmeister/kafka
        ports:
          - containerPort: 9092
        env:
          - name: KAFKA_ADVERTISED_HOST_NAME
            value: 10.96.41.4
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: zookeeper:2181
        volumeMounts:
          - mountPath: /var/run/docker.sock
            name: kafka-volume
      volumes:
        - name: kafka-volume
          hostPath:
            path: /var/run/docker.sock
            type: FileOrCreate
---



