version: "3.1"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "60000-60200:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.17.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  jobmanager:
    image: ${FLINK_DOCKER_IMAGE_NAME:-flink}
    expose:
      - "6123"
    ports:
      - "8081:8081"
    entrypoint: /bin/sh -c
    command:
      - /bin/sh /docker-entrypoint.sh jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    env_file:
      - .env

  taskmanager:
    image: ${FLINK_DOCKER_IMAGE_NAME:-flink}
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    entrypoint: /bin/sh -c
    command:
      - /bin/sh /docker-entrypoint.sh taskmanager
      - chmod -R 777 /home/createdFiles
    links:
      - "jobmanager:jobmanager"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    env_file:
      - .env
    volumes:
      - /var/tmp/createdFiles:/home/createdFiles
  postgres:
    image: postgres
    restart: always
    env_file:
      - postgres-setup.env
    entrypoint: /bin/sh -c
    command:
      - /docker-entrypoint.sh postgres
    volumes:
      - /var/tmp/postgres-sql-import.d:/docker-entrypoint-initdb.d
    ports:
      - 5433:5432